<a href="https://colab.research.google.com/github/ashikshafi08/Learning_Tensorflow/blob/main/Exericse_and_Extra-curriculum/00_TensorFlow_Fundamentals_%F0%9F%9B%A0_Exercises_%26_%F0%9F%93%96_Extra_curriculum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


# Exercise 

## 🛠 00 TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the **shape**, **rank** and **size** of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using **matrix multiplication**.
5. Multiply the two tensors you created in 3 using **dot product**.
6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.
7. Find the **min** and **max values** of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.
10. **One-hot** encode the tensor you created in 9.

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.


In [2]:
# Creating a scalar 
scalar = tf.constant([8])

# Creating a vector 
vector = tf.constant([1 , 2 , 3])

# Creating a matrix 
matrix = tf.constant([[1 ,2] , 
                      [3, 4]])

# Creating a tensor 
tensor = tf.constant([[10 , 9 , 8] , 
                      [1 ,2 , 4], 
                      [8 , 4 , 2]])

scalar , vector , matrix , tensor 

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  9,  8],
        [ 1,  2,  4],
        [ 8,  4,  2]], dtype=int32)>)

### 2. Find the **shape**, **rank** and **size** of the tensors you created in 1.

In [3]:
# Finding the shape, rank and size
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (3, 3)
The rank of the tensor: 9
The rank of the tensor: 2


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.


In [4]:
tensor_1 = tf.random.Generator.from_seed(20)
tensor_2 = tf.random.Generator.from_seed(20)

# Setting up the shape 
tensor_1 = tensor_1.normal(shape =(5 , 100))
tensor_2 = tensor_2.normal(shape = (5 , 100))

tensor_1.shape , tensor_2.shape

(TensorShape([5, 100]), TensorShape([5, 100]))

### 4. Multiply the two tensors you created in 3 using **matrix multiplication**.


In [5]:
# Multiplying

print('Shape before the matrix multiplication')
print(tensor_1.shape , '\n')
print(tensor_2.shape , '\n')

resultant_vector = tf.linalg.matmul(tensor_1 , tf.transpose(tensor_2))
print(f'After multiplying the resultant vector is: {resultant_vector} \n')

print(f'The resultant vector shape: {resultant_vector.shape}')

Shape before the matrix multiplication
(5, 100) 

(5, 100) 

After multiplying the resultant vector is: [[ 1.1152011e+02 -2.0163528e+01  7.6871336e-02  5.8260102e+00
   1.3360726e+01]
 [-2.0163528e+01  1.0469975e+02 -8.7291698e+00  8.0652893e-01
  -6.5397663e+00]
 [ 7.6871336e-02 -8.7291698e+00  8.7304695e+01  4.6838622e+00
  -1.9468361e+01]
 [ 5.8260102e+00  8.0652893e-01  4.6838622e+00  8.9833633e+01
  -8.1998968e+00]
 [ 1.3360726e+01 -6.5397663e+00 -1.9468361e+01 -8.1998968e+00
   1.0752870e+02]] 

The resultant vector shape: (5, 5)


### 5. Multiply the two tensors you created in 3 using **dot product**.


In [6]:
# Using tensordot

tf.tensordot(tensor_1 , tf.transpose(tensor_2) , axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.1152011e+02, -2.0163528e+01,  7.6871336e-02,  5.8260102e+00,
         1.3360726e+01],
       [-2.0163528e+01,  1.0469975e+02, -8.7291698e+00,  8.0652893e-01,
        -6.5397663e+00],
       [ 7.6871336e-02, -8.7291698e+00,  8.7304695e+01,  4.6838622e+00,
        -1.9468361e+01],
       [ 5.8260102e+00,  8.0652893e-01,  4.6838622e+00,  8.9833633e+01,
        -8.1998968e+00],
       [ 1.3360726e+01, -6.5397663e+00, -1.9468361e+01, -8.1998968e+00,
         1.0752870e+02]], dtype=float32)>

### 6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.


In [7]:
# Tensor with shape [224 , 224 , 3]
big_tensor = tf.random.Generator.from_seed(42)
big_tensor = big_tensor.normal(shape = (224 , 224 , 3))

big_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ],
        ...,
        [ 0.07099114, -0.5095768 ,  0.3482001 ],
        [ 0.15985982, -1.9042184 ,  0.9690504 ],
        [ 0.16251186, -0.07330751, -0.36059096]],

       [[ 0.18739441, -0.73353654,  1.2104433 ],
        [ 1.5603006 , -0.48115277,  0.6335167 ],
        [-0.5612103 ,  0.06994031,  1.6807095 ],
        ...,
        [-1.9460293 , -0.7977275 ,  0.03092833],
        [ 0.8297488 ,  0.12179119,  1.0506107 ],
        [-1.3097638 ,  0.92536974, -1.1787732 ]],

       [[-0.21711825, -0.73974085, -1.3077081 ],
        [-0.7502274 , -0.37715855, -0.30130875],
        [ 1.0943383 ,  0.255803  ,  0.8011465 ],
        ...,
        [-0.32833767, -0.7794747 ,  0.20049337],
        [-0.09002841,  0.07243237, -0.81940895],
        [ 0.3171264 , -1.6143694 , -1.6824652 ]],

       ...,

     

### 7. Find the **min** and **max values** of the tensor you created in 6.


In [8]:
# Finding the minimum 

minimum = tf.math.reduce_min(big_tensor)
print(f'The minimum value is: {minimum}')

The minimum value is: -4.848316192626953


In [9]:
# Finding the maximum 
maximum = tf.math.reduce_max(big_tensor)
print(f'The maximum value is: {maximum}')

The maximum value is: 4.403286457061768


### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.


In [10]:
# Tensor with shape [224 , 224 , 3]
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape = (1 , 224 , 224 , 3))

print(f'The shape before squeezing: {unsqueezed_tensor.shape}')

The shape before squeezing: (1, 224, 224, 3)


In [11]:
# And we are squeezing it 
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f'The shape after squeezing: {squeezed_tensor.shape}')

The shape after squeezing: (224, 224, 3)


### 9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.


In [12]:
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])

# Finding the index where value is maximum 
max_value = tf.math.argmax(ten_tensor)

print(f'The indices where the value is maximum: {max_value}')
print(f'The maximum value was: {ten_tensor[max_value]}')

The indices where the value is maximum: 6
The maximum value was: 10.0


### 10. **One-hot** encode the tensor you created in 9.

In [13]:
# Throw's an error since I had floating numbers in my tensor, casting to int solved! 
tf.cast(ten_tensor , dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  9, 10,  0,  0,  6], dtype=int32)>

In [14]:
# One hot encoding the tensor of shape 10 
tf.one_hot(tf.cast(ten_tensor , dtype=tf.int32) , depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

## Extra Curriculum 

- Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
    - How would you calculate your grocery bill for the month and for the year using tensors?