<a href="https://colab.research.google.com/github/ashikshafi08/Learning_Tensorflow/blob/main/Exercise%20Solutions/%F0%9F%9B%A0%2000_TensorFlow_Fundamentals_Exercises_%26_%F0%9F%93%96_Extra_curriculum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


# Exercise 

## 🛠 00 TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the **shape**, **rank** and **size** of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using **matrix multiplication**.
5. Multiply the two tensors you created in 3 using **dot product**.
6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.
7. Find the **min** and **max values** of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.
10. **One-hot** encode the tensor you created in 9.

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.


In [ ]:
# Creating a scalar 
scalar = tf.constant([8])

# Creating a vector 
vector = tf.constant([1 , 2 , 3])

# Creating a matrix 
matrix = tf.constant([[1 ,2] , 
                      [3, 4]])

# Creating a tensor 
tensor = tf.constant([[10 , 9 , 8] , 
                      [1 ,2 , 4], 
                      [8 , 4 , 2]])

scalar , vector , matrix , tensor 

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  9,  8],
        [ 1,  2,  4],
        [ 8,  4,  2]], dtype=int32)>)

### 2. Find the **shape**, **rank** and **size** of the tensors you created in 1.

In [ ]:
# Finding the shape, rank and size
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (3, 3)
The rank of the tensor: 9
The rank of the tensor: 2


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.


In [ ]:
tensor_1 = tf.random.Generator.from_seed(20)
tensor_2 = tf.random.Generator.from_seed(20)

# Setting up the shape 
tensor_1 = tensor_1.normal(shape =(5 , 100))
tensor_2 = tensor_2.normal(shape = (5 , 100))

tensor_1.shape , tensor_2.shape

(TensorShape([5, 100]), TensorShape([5, 100]))

### 4. Multiply the two tensors you created in 3 using **matrix multiplication**.


In [ ]:
# Multiplying

print('Shape before the matrix multiplication')
print(tensor_1.shape , '\n')
print(tensor_2.shape , '\n')

resultant_vector = tf.linalg.matmul(tensor_1 , tf.transpose(tensor_2))
print(f'After multiplying the resultant vector is: {resultant_vector} \n')

print(f'The resultant vector shape: {resultant_vector.shape}')

Shape before the matrix multiplication
(5, 100) 

(5, 100) 

After multiplying the resultant vector is: [[ 1.1152011e+02 -2.0163528e+01  7.6871336e-02  5.8260102e+00
   1.3360726e+01]
 [-2.0163528e+01  1.0469975e+02 -8.7291698e+00  8.0652893e-01
  -6.5397663e+00]
 [ 7.6871336e-02 -8.7291698e+00  8.7304695e+01  4.6838622e+00
  -1.9468361e+01]
 [ 5.8260102e+00  8.0652893e-01  4.6838622e+00  8.9833633e+01
  -8.1998968e+00]
 [ 1.3360726e+01 -6.5397663e+00 -1.9468361e+01 -8.1998968e+00
   1.0752870e+02]] 

The resultant vector shape: (5, 5)


### 5. Multiply the two tensors you created in 3 using **dot product**.


In [ ]:
# Using tensordot

tf.tensordot(tensor_1 , tf.transpose(tensor_2) , axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.1152011e+02, -2.0163528e+01,  7.6871336e-02,  5.8260102e+00,
         1.3360726e+01],
       [-2.0163528e+01,  1.0469975e+02, -8.7291698e+00,  8.0652893e-01,
        -6.5397663e+00],
       [ 7.6871336e-02, -8.7291698e+00,  8.7304695e+01,  4.6838622e+00,
        -1.9468361e+01],
       [ 5.8260102e+00,  8.0652893e-01,  4.6838622e+00,  8.9833633e+01,
        -8.1998968e+00],
       [ 1.3360726e+01, -6.5397663e+00, -1.9468361e+01, -8.1998968e+00,
         1.0752870e+02]], dtype=float32)>

### 6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.


In [7]:
# Tensor with shape [224 , 224 , 3]
big_tensor = tf.random.uniform(shape = [224 , 224 , 3], minval = 0 , maxval = 1)

big_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.16492105, 0.2753117 , 0.9938582 ],
        [0.28192294, 0.15807188, 0.8429942 ],
        [0.84264314, 0.32728314, 0.15411282],
        ...,
        [0.5070746 , 0.30085158, 0.95198715],
        [0.97285366, 0.5184705 , 0.37301648],
        [0.6792079 , 0.58873427, 0.29493403]],

       [[0.49952328, 0.43266344, 0.9816874 ],
        [0.27082694, 0.6951047 , 0.9915391 ],
        [0.2062366 , 0.6174034 , 0.12117112],
        ...,
        [0.49763942, 0.38546133, 0.60577035],
        [0.03882432, 0.45464218, 0.34204078],
        [0.99874127, 0.3193239 , 0.9990982 ]],

       [[0.82930887, 0.6980667 , 0.38108087],
        [0.92087865, 0.40597975, 0.26164782],
        [0.56127524, 0.3887844 , 0.7102684 ],
        ...,
        [0.45595026, 0.11628592, 0.44341063],
        [0.9181205 , 0.6624149 , 0.6607721 ],
        [0.9167942 , 0.6085763 , 0.84494877]],

       ...,

       [[0.91161656, 0.38026464, 0.26940346],
        [0.45

In [8]:
# Checking the min and max value of our tensor 
print(f'Maximum value: {tf.reduce_max(a)}')
print(f'Minimum value: {tf.reduce_min(a)}')


Maximum value: 0.9999923706054688
Minimum value: 2.1576881408691406e-05


### 7. Find the **min** and **max values** of the tensor you created in 6.


In [ ]:
# Finding the minimum 

minimum = tf.math.reduce_min(big_tensor)
print(f'The minimum value is: {minimum}')

The minimum value is: -4.848316192626953


In [ ]:
# Finding the maximum 
maximum = tf.math.reduce_max(big_tensor)
print(f'The maximum value is: {maximum}')

The maximum value is: 4.403286457061768


### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.


In [ ]:
# Tensor with shape [224 , 224 , 3]
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape = (1 , 224 , 224 , 3))

print(f'The shape before squeezing: {unsqueezed_tensor.shape}')

The shape before squeezing: (1, 224, 224, 3)


In [ ]:
# And we are squeezing it 
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f'The shape after squeezing: {squeezed_tensor.shape}')

The shape after squeezing: (224, 224, 3)


### 9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.


In [ ]:
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])

# Finding the index where value is maximum 
max_value = tf.math.argmax(ten_tensor)

print(f'The indices where the value is maximum: {max_value}')
print(f'The maximum value was: {ten_tensor[max_value]}')

The indices where the value is maximum: 6
The maximum value was: 10.0


### 10. **One-hot** encode the tensor you created in 9.

In [ ]:
# Throw's an error since I had floating numbers in my tensor, casting to int solved! 
tf.cast(ten_tensor , dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  9, 10,  0,  0,  6], dtype=int32)>

In [ ]:
# One hot encoding the tensor of shape 10 
tf.one_hot(tf.cast(ten_tensor , dtype=tf.int32) , depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

## Extra Curriculum 

- Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
    - How would you calculate your grocery bill for the month and for the year using tensors?