<a href="https://colab.research.google.com/github/ashikshafi08/Learning_Tensorflow/blob/main/Notebooks/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) 

2.4.1


# Tensorflow Fundamentals 

In this notebook we are going to cover some of the fundamentals concepts of tensors using **TensorFlow**. 

Let's draw the outline what we are going to see, 
- Introduction to tensors 
- Getting information from tensors
- Manipulating tensors 
- Tensors and Numpy 
- Using `@tf.function`, a way to speed up regular python functions with tensorflow. 
- Using GPU's (or TPU's) with Tensorflow. 
- Exercise to muscle up tensorflow fundamentals skills.


## Introduction to tensors 

#### **Using `tf.constant` to create tensors**

In [ ]:
# Creating tensors with tf.constant 

scalar = tf.constant(7)
scalar # Creating a scalar tensor

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the number of dimensions of tensors 
scalar.ndim # No of dimensions

0

In [ ]:
# Create a vector 
vector = tf.constant([10 , 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Checking the dimensions now 
vector.ndim 

1

In [ ]:
# Now creating a matrix (has more than 1 dimensions)
matrix = tf.constant( [[1 , 2] , 
                       [3, 4]] )

matrix 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Checking the dimensions now 
matrix.ndim 

2

In [ ]:
# Now manually choosing the dtype, and creating a matrix 

new_mat = tf.constant([ [1. , 2.] , 
                       [3. , 4.], 
                       [5. , 6.]] , dtype = tf.float16)
new_mat

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

There's not huge difference between `dtype = float32` and `dtype = float16`, it's mostly focuses on the memory allocation. 

Where `dtype = float32` storing these takes up larger space whereas `dtype = float16` takes up less space. 

We can use this to debug **datatype errors** or tensors being in wrong datatype, using this could fix it.

- Scalar --> Has 1 dimension
- Vector --> Has 2 dimensions
- Tensor --> Has 3 dimensions

In [ ]:
# Now checking the dimensions of the above matrix 
new_mat.ndim

2

In [ ]:
# Creating a tensor with more dimension

tensor = tf.constant([[[1 , 2 ,3],
                       [4,5,6]],
                      
                      [[7 , 8 , 9],
                       [10 , 11 , 12]],
                      
                      [[13 , 14 , 15] ,
                       [16 , 17 , 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

- Scalar : a single number 
- Vector : a number with direction 
- Matrix : a 2-dimensional array of numbers 
- Tensor : a n-dimensional array of numbers (where n can be any numbers)

#### **Using `tf.Variable` to create tensors** 

Let's call this changeable tensor, alike is Javascript using var brings us options on overwriitng or make changes to the tensor. 

But when we use const for creating a tensor, this reduces the chances of altering the tensor. 

In [ ]:
changeable_tensor = tf.Variable([10 , 4])

# Creating one with constant
unchangeable_tensor = tf.constant([10 , 4])

changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>)

Making changes using `tf.Variable` using the `.assign()` function.

In [ ]:
# Changing the value of the tensor 
changeable_tensor[0].assign(7)

# Looking into our tensor after changes 
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Now trying the same in our unchangeable_tensor 

# unchangeable_tensor[0].assign(7) Throws error, uncomment to check the error.

Well it's obvious that we can't alter the tensor which are created using `tf.constant`. But why two ways of creating tensors exist even? 

Well while a Neural Net is been created, there are values should be changed whenever we want to and there should certain tensors locked up so that no one could make their changes on it. 

It might feel bit hectic, but good thing is that we need not to worry about assigning or structuring our neural net what values should it change and what it shouldn't. 

Behind the scenes these are taken care by TensorFlow.

#### **Creating random tensors**

Random tensors are tensors of some arbitary size which contain random numbers. 

In [ ]:
# Creating 2 random (but same size)
random_1 = tf.random.Generator.from_seed(42)
random_2 = tf.random.Generator.from_seed(42)

# Giving in the shapes of how we want our tensors 
random_1 = random_1.normal(shape = (3,2))
random_2 = random_2.normal(shape = (3,2))

In [ ]:
# Are they equal? 

random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Alright seems those two tensors are equal, but we asked for random tensors yet we got both of em equal, but why? 

In fact the values inside the random tensors aren't actually random, they are called as **pseudo values** which means they are getting geenrated because of the `from_seed()`.

It seeds the combinations and tensors depending upon the number we put it, this is because to attain reproducibility.

But how we fix this? If we can shuffle the order between them then they wont be identical. 



#### **Shuffling the order of tensors**

Shuffling comes in handy to prevent class Imbalance, which means if we fed images into a Neural Net in a strict plain order for instance, 

- Ramen (5000 pics)
- Cookie (1000 pics) 

Reading the images starting from Ramen and ends all of the 5000 pics and jumps next to Cookie, this won't give much work to our weight assignment. 

But if we can shuffle the images, our weights would be able to learn different classes at the same time. 

Now let's shuffle our tensors, valuable for when we want to shuffle our data so the inherent order won't affect our learning.

In [ ]:
# Creating a tensor to shuffle

not_shuffled = tf.constant([[10 ,4],
                            [9 , 3],
                            [5 , 8]])

not_shuffled , not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  4],
        [ 9,  3],
        [ 5,  8]], dtype=int32)>, 2)

In [ ]:
# Shuffling the tensor 
tf.random.shuffle(not_shuffled) # The order will be changed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  3],
       [10,  4],
       [ 5,  8]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled) # The order will be changed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [10,  4],
       [ 9,  3]], dtype=int32)>

If we look into the shuffled and not_shuffled tensors we could find a common pattern that,
* Randomly shuffles a tensor along it's first dimension.

Which means it just changes the order of the rows, not the whole of the values inside the tensor. 

Also if we notice the two cells above with the same code `tf.random.shuffle(not_shuffled)`, the order is changed everytime when we run the cell.

**Using seed in the above shuffled example**

In [ ]:
# Using the argument one 
tf.random.shuffle(not_shuffled , seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 9,  3],
       [10,  4]], dtype=int32)>

In [ ]:
# Using a funciton called set_seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  3],
       [ 5,  8],
       [10,  4]], dtype=int32)>

In [ ]:
# Creating 2 new tensor to play with 

#new_1_tensor = tf.random.Generator.from_seed(2)
#new_2_tensor = tf.random.Generator.from_seed(2)

# Now setting up the shape 
normal_tensor = tf.random.normal(shape = (3 , 2) , dtype = tf.float16) # (normal distributed values)
uniform_tensor = tf.random.normal(shape= (3 , 2) ,  dtype = tf.float16) # (uniformly distributed values)

normal_tensor , uniform_tensor


(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 0.0842  , -0.861   ],
        [ 0.3782  , -0.005196],
        [-0.4946  ,  0.6177  ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[-0.559 , -0.5347],
        [ 2.373 , -1.572 ],
        [ 0.8057, -0.834 ]], dtype=float16)>)

From reading the documentations, I understood about `tf.random.set_seed()`  is,  whenever we write that at first and the following code inside that cell will be generated with the same seed state. 




In [ ]:
# Let's shuffle them! 

tf.random.set_seed(59) # Setting the seed here

# Shuffling 
norm_shuff = tf.random.shuffle(normal_tensor)
uni_shuff = tf.random.shuffle(uniform_tensor)

norm_shuff , uni_shuff

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 0.3782  , -0.005196],
        [-0.4946  ,  0.6177  ],
        [ 0.0842  , -0.861   ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 2.373 , -1.572 ],
        [-0.559 , -0.5347],
        [ 0.8057, -0.834 ]], dtype=float16)>)

In [ ]:
# Now using the argument one 

tf.random.shuffle(normal_tensor , seed = 32) , tf.random.shuffle(uniform_tensor , seed = 32)

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 0.0842  , -0.861   ],
        [ 0.3782  , -0.005196],
        [-0.4946  ,  0.6177  ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[-0.559 , -0.5347],
        [ 0.8057, -0.834 ],
        [ 2.373 , -1.572 ]], dtype=float16)>)

In [ ]:
# Using global and operation level both in conjuction

tf.random.set_seed(34) # Global level 
tf.random.shuffle(normal_tensor , seed=34)


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 0.0842  , -0.861   ],
       [-0.4946  ,  0.6177  ],
       [ 0.3782  , -0.005196]], dtype=float16)>

Alright summing up using, `tf.random.shuffle(any_tensor , seed = 32)` doesn't works. The results aren't reproducible. 

But when we use `tf.random.set_seed(42)`, the entire code written / wrapped inside that cell uses the seed rate and the results are reproducible. 

And using `tf.random.shuffle(any_tensor)` only shuffles the tensor along the **1st dimension**, which means just shuffles the rows. 

It look's like if we want our shuffled tensors to be in same order, we've got to use the global level and operation level random seed.

> If both the global and the operation seed arse set: Both seeds are used in conjuction to determine the random sequence.


#### **Creating Tensors from Numpy Array**

Certain functions of Numpy are even in TensorFlow, will look at them. 

In [ ]:
# Creating a tensor of all ones / Numpy (np.ones) 

tf.ones([10 , 4]) # Pass in the shape

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Creating tensor for all zeros / Same numpy 

tf.zeros([8 , 5])

<tf.Tensor: shape=(8, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

**X** ---> Capital for matrix and tensors.
**y** ----> non-capital for vector.

In [ ]:
# Turning numpy array into tensors
import numpy as np
numpy_A = np.arange(1 , 25 , dtype = np.float32)
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [ ]:
# Putting into tf.constant converting into tensor
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)>

In [ ]:
# Now using our desired shape as we need 

A = tf.constant(numpy_A , shape = (2 ,4 ,3))
B = tf.constant(numpy_A)

A , B

(<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],
 
        [[13., 14., 15.],
         [16., 17., 18.],
         [19., 20., 21.],
         [22., 23., 24.]]], dtype=float32)>,
 <tf.Tensor: shape=(24,), dtype=float32, numpy=
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float32)>)

In [ ]:
tf.constant(numpy_A , shape = (3 , 8))


<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float32)>

If we look above, the shape should be decided with respect to the number of elements available in total. 

For instance, above we got **24 elements** and Creating different shapes we gotta makse sure are they equal when we multilply them

#### **Getting information from the tensors --> Tensor Attributes**

The common attributes we gotta keep an eye out are: 
- Shape 
- Rank 
- Size 
- Axis or dimension

In [ ]:
# Creating a rank 4 tensor 

rank_4_tensor = tf.zeros(shape = [2 , 3 , 4 ,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Indexing into the above tensor 
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# Printing out certain attributes for the above tensor 

def tensor_attr_print(a_tensor):
  '''
  Print's out different attribures of a tensor
  '''
  rank_4_tensor = a_tensor
  print(f'Elements along the 0th axis: {rank_4_tensor.shape[0]}')
  print(f'Elements along the last axis: {rank_4_tensor.shape[-1]}')
  print(f'Datatype of every element: {rank_4_tensor.dtype}')

  print(f'The shape of the tensor is: {rank_4_tensor.shape}')
  print(f'The dimension of the tensor is: {rank_4_tensor.ndim}')
  print(f'The size of the tensor(total no. of elements in the tensor): {tf.size(rank_4_tensor)}')

In [ ]:
tensor_attr_print(rank_4_tensor)

Elements along the 0th axis: 2
Elements along the last axis: 5
Datatype of every element: <dtype: 'float32'>
The shape of the tensor is: (2, 3, 4, 5)
The dimension of the tensor is: 4
The size of the tensor(total no. of elements in the tensor): 120


#### **Indexing and expanding tensors**

Tensors can be indexed just like Python list's

In [ ]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2 , :2 , :2 , :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# Get the first element from each dimensionn from each index except for the final one 

rank_4_tensor[:1 , :1 , :1 , :] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1 , :1 , : , :1] # Since the shape is 4

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1 , : , :1 , :1] # Since the shape is 3

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
# Creating a rank 2 tensor

rank_2_tensor = tf.constant([[10 , 11] , 
                             [9 , 5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [ 9,  5]], dtype=int32)>

In [ ]:
# Getting some attributes about the rank_2_tensor
tensor_attr_print(rank_2_tensor)

Elements along the 0th axis: 2
Elements along the last axis: 2
Datatype of every element: <dtype: 'int32'>
The shape of the tensor is: (2, 2)
The dimension of the tensor is: 2
The size of the tensor(total no. of elements in the tensor): 4


In [ ]:
# Get the last item of each row out of rank 2 tensors
rank_2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([11,  5], dtype=int32)>

Adding another dimension to a tensor by storing exactly the information on `rank_3_tensor` using `tf.newaxis`

- `...` --> every axis before the last one.
- `tf.newaxis` --> add a newaxis at the end


In [ ]:
# Turning rank 2 into rank 3 tensor
rank_3_tensor = rank_2_tensor[... , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [11]],

       [[ 9],
        [ 5]]], dtype=int32)>

There is an alternative to `tf.newaxis` which is called as `tf.expand_dims()`.

In [ ]:
# Using tf.expand_dims 

tf.expand_dims(rank_2_tensor , axis=-1) # -1 means expand at the final axis.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [11]],

       [[ 9],
        [ 5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor , axis = 0) # expand the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 11],
        [ 9,  5]]], dtype=int32)>

The information remains the same, but the way of storing them changes.

#### **Manipulating Tensors (Tensor Operations)**

**Basic Operations**
- `+`
- `-`
- `*` etc..

We can add values to a tensor using the addition operator

In [ ]:
# Using the addition operator
tensor = tf.constant([[10 , 7] , 
                      [9 , 4]])

tensor + 10 # Adding + 10 to our tensor, it adds every element in a tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [19, 14]], dtype=int32)>

In [ ]:
# Trying out multiplication and subtraction
tensor * 2 , tensor - 4

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 14],
        [18,  8]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 3],
        [5, 0]], dtype=int32)>)

We can also use built-in tensorflow functions

In [ ]:
# For multiplication 
tf.math.multiply(tensor , 10) # (one number , another number to multiply)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 90,  40]], dtype=int32)>

In [ ]:
# Using tf.add and subtract 

tf.math.add(tensor , 30) , tf.math.subtract(tensor , 303)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[40, 37],
        [39, 34]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-293, -296],
        [-294, -299]], dtype=int32)>)

In [ ]:
# Getting the tan of our tensor 
x = tf.constant([-float("inf"), -5, -0.004, 5, 3.2, 23400, 1000000, float("inf")])

tf.math.tan(x)

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([           nan,  3.3805151e+00, -4.0000216e-03, -3.3805151e+00,
        5.8473900e-02,  6.4900270e+00, -3.7362447e-01,            nan],
      dtype=float32)>

#### **Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we are going to use matrix multiplication. 

* The inner dimensions should match.
* The resulting matrix has the shape of the outer dimensions. 


In [ ]:
# For matrix multi we use tf.linalg.matmul , Using Tensorflow

print(tensor)
tf.linalg.matmul(tensor , tensor) # multiplying both tensors 

tf.Tensor(
[[10  7]
 [ 9  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[163,  98],
       [126,  79]], dtype=int32)>

In [ ]:
# Trying basic * operator 

tensor * tensor # doesn't perform matrix way of multiplying

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 81,  16]], dtype=int32)>

In [ ]:
# Matrix Multiplication with Python operator @

tensor @ tensor # @ --> matrix mutliplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[163,  98],
       [126,  79]], dtype=int32)>

In [ ]:
# Recreating tensors from matrix multiplication.xyz 

a = tf.constant([[1 , 2 ,5], 
                 [7 , 2 , 1],
                 [3, 3, 3]])

b = tf.constant([[3 , 5] , 
                 [6 , 7], 
                 [1 , 8]])

# Using matmul 
tf.linalg.matmul(a , b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

Performing matrix multiplication on tensors with different shape. 

In [ ]:
# Create a tensor of (3 , 4) an (4 , 6)

a = tf.constant([[1 , 2 ,3 ,4] , 
                [4 , 6, 1 , 100] , 
                 [58 , 5 , 0 , 3]])

b =  tf.constant([[1 , 2 ,3 ,4 , 5 , 3 ] , 
                [4 , 6, 1 , 100 , 5 , 0] , 
                 [58 , 5 , 0 , 3 , 1 , 303] , 
                  [0 , 2 , 3 ,5 , 2 , 8]])
a , b


(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[  1,   2,   3,   4],
        [  4,   6,   1, 100],
        [ 58,   5,   0,   3]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[  1,   2,   3,   4,   5,   3],
        [  4,   6,   1, 100,   5,   0],
        [ 58,   5,   0,   3,   1, 303],
        [  0,   2,   3,   5,   2,   8]], dtype=int32)>)

In [ ]:
# Using matmul 
tf.linalg.matmul(a , b)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 183,   37,   17,  233,   26,  944],
       [  86,  249,  318, 1119,  251, 1115],
       [  78,  152,  188,  747,  321,  198]], dtype=int32)>

In [ ]:
# Using @  
a @ b # Slow compared to tensorflow function

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 183,   37,   17,  233,   26,  944],
       [  86,  249,  318, 1119,  251, 1115],
       [  78,  152,  188,  747,  321,  198]], dtype=int32)>

Trying with tensor of same size 

In [ ]:
# Two tensors of (3, 2)  

x = tf.constant([[1 , 2] , 
                 [3 , 4] , 
                 [9 , 2]])

y = tf.constant([[5 , 6] , 
                 [8 , 9] , 
                 [3 , 2]])

x , y  # same size 

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [9, 2]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [8, 9],
        [3, 2]], dtype=int32)>)

In [ ]:
# Trying to matix multiply using @ 
# x @ y  --> throws error

In [ ]:
# Using matmul

# tf.matmul(x , y) # Throws an error

Will try to use `tf.reshape` to change the shape of the tensor, so that it's inner dimensions matches.


In [ ]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 9],
       [3, 2]], dtype=int32)>

In [ ]:
# Changing the shape 
y_changed = tf.reshape(y , shape=(2 , 3))
y_changed

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 6, 8],
       [9, 3, 2]], dtype=int32)>

In [ ]:
x.shape , y_changed.shape # Inner dimensions match

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Now multiplying 

x @ y_changed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 12, 12],
       [51, 30, 32],
       [63, 60, 76]], dtype=int32)>

In [ ]:
# Using matmul 

tf.linalg.matmul(x , y_changed)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 12, 12],
       [51, 30, 32],
       [63, 60, 76]], dtype=int32)>

In [ ]:
x.shape , y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
# Now changing x instead of y 
tf.matmul(tf.reshape(x , shape=(2 , 3)) , y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 30,  30],
       [ 98, 109]], dtype=int32)>

In [ ]:
# But why 2x2 matrix ? 
tf.reshape(x , shape=(2 ,3)).shape , y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

Using `tf.transpose` which flips the axis. 

`tf.reshape` --> shuffles the tensor to reshape the tensor along.

In [ ]:
# Using transpose and performing matrix multi

tf.linalg.matmul(x , tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 26,  7],
       [39, 60, 17],
       [57, 90, 31]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also reffered to as dot product. We can perform matrix multiplication using:

- `tf.matmul(a , b)`
- `tf.tensordot()` does similar

In [ ]:
# Perform the dot product on X and Y (requires X to be transposed)

tf.tensordot(tf.transpose(x) , y , axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[56, 51],
       [48, 52]], dtype=int32)>

In [ ]:
# Perform a matrix multiplication between x and y (transpose)

tf.linalg.matmul(x , tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 26,  7],
       [39, 60, 17],
       [57, 90, 31]], dtype=int32)>

In [ ]:
# Perform a matrix multiplication between x and y (reshape)

tf.linalg.matmul(x , tf.reshape(y , shape= (2 , 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 12, 12],
       [51, 30, 32],
       [63, 60, 76]], dtype=int32)>

In [ ]:
# Debugging 

# Normal y 
print(f'This is the normal y: ')
print(y , '\n')

# Transposed y 
print('This is the transposed y: ')
print(tf.transpose(y) , '\n')

# Reshaped y 
print('This is the reshaped y: ')
print(tf.reshape(y , shape=(2 ,3)) , '\n')

This is the normal y: 
tf.Tensor(
[[5 6]
 [8 9]
 [3 2]], shape=(3, 2), dtype=int32) 

This is the transposed y: 
tf.Tensor(
[[5 8 3]
 [6 9 2]], shape=(2, 3), dtype=int32) 

This is the reshaped y: 
tf.Tensor(
[[5 6 8]
 [9 3 2]], shape=(2, 3), dtype=int32) 



Generally, when performing matrix multiplication on two tensors and one of them axes doesn't line up, we will transpose (rather than reshape) the tensors to get satisfy the matrix multiplication.

#### **Changing the datatype of tensors**

There will be times where we gotta change the datatype of our tensor.

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

In [ ]:
# Create a new tensor with default dtype (float32)

A = tf.constant([1.9 , 5]) # got one floating value
A.dtype

tf.float32

In [ ]:
B = tf.constant([1 , 3])
B.dtype # No floating value 

tf.int32

If the tensor has floating values in it, the tensor will be considered as a `float32` tensor. And when we got only integers then the dtype will be `int32`.

In [ ]:
# Change from float32 to float16 -- called reduced precision
# We can change the dtype using tf.cast

A_cast = tf.cast(A , dtype=tf.float16)

# Checking the dtype after casting vs before casting
A_cast.dtype , A.dtype


(tf.float16, tf.float32)

By deducing from `float32` to `float16` for quite a million of tensor means we have halved the memory allocation of those tensors. More like easing things for our GPU not putting loads of memory on it.

In [ ]:
# Change from int32 to float32 

print('Before Casting')
print(B.dtype , '\n')

print('After Casting')
E = tf.cast(B , dtype=tf.float16)
print(E.dtype , '\n')

Before Casting
<dtype: 'int32'> 

After Casting
<dtype: 'float16'> 



#### **Aggregating Tensors**

*Aggregating Tensors* --> Condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Creating a tensor 

new_tensor = tf.constant([[1 , -39 , -23] , 
                          [-12 , 2 , -1]])
new_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  1, -39, -23],
       [-12,   2,  -1]], dtype=int32)>

In [ ]:
# Getting the absolute values 
# abs --> remove -ve replaced by +ve of that value. 

tf.abs(new_tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 39, 23],
       [12,  2,  1]], dtype=int32)>

Let's go through the following forms of aggregation: 

* Get the minimum 
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Using a new tensor 

agg_tensor = tf.constant(np.random.randint(0 , 100 , 50))
agg_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([66, 23,  2,  9, 82, 43, 31, 13, 77, 59, 16, 48, 42,  0, 42, 81, 45,
        6, 56, 75, 21, 30, 39, 78, 89,  9, 68, 74, 72, 86, 71, 96, 85,  2,
       16, 61, 77, 33, 10, 42, 79, 96, 20, 51, 35, 18, 30, 44, 72, 20])>

In [ ]:
# Getting the minimum 

tf.math.reduce_min(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Getting the maximum 
tf.math.reduce_max(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
# Getting the mean of a tensor 
tf.math.reduce_mean(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [ ]:
# Getting the sum of a tensor 
tf.math.reduce_sum(agg_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2340>

In [ ]:
# Getting the variance in our tensor 
# Variance --> denotes the spread in our data

tf.math.reduce_variance(tf.cast(agg_tensor , dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=809.0>

In [ ]:
# Getting the standard deivation of our tensor 

tf.math.reduce_std(tf.cast(agg_tensor , dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.44>

#### **Finding the positional maximum and minimum**

Will help us to find at which index or row of a tensor does the maximum or minimum value occur. It gives back the index of the value which can be used during our ouput representation.

In [ ]:
# Creating a new tensor 

tf.random.set_seed(42)
out = tf.random.uniform(shape=[50])
out

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Finding the positional maximum --> gives out the output

tf.argmax(out)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Now getting the exact values 
out[tf.argmax(out)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Cross checking 

tf.math.reduce_max(out)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Checking for equality 
# assert --> throws error if not equal 

assert out[tf.argmax(out)] == tf.math.reduce_max(out)

In [ ]:
# Find the positional minimum
out[tf.argmin(out)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#### **Squeezing a tensor (removing all 1-dimension axes)**

In [ ]:
sq_tensor = tf.constant(out , shape=[1 , 1, 1, 1, 50])
sq_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
# Shape of the tensor 
sq_tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# Creating a squeezed version of our tensor 
# squeeze --> removes dimensions of the size 1 from the tensor

sq_tensor_unsqueezed = tf.squeeze(sq_tensor)
sq_tensor_unsqueezed , sq_tensor_unsqueezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

In [ ]:
# Comparing tensors 

sq_tensor.shape , sq_tensor_unsqueezed.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

#### **One hot encoding tensors**

It's a way of numerical encoding of our strings / words in a way our neural network could understand. 

In [ ]:
# Creating a dummy list of indices

some_lists = [0 , 1 , 2 , 3]

# Now one hot encoding it 
tf.one_hot(some_lists , depth = 4) # depth --> how many variable's we have (4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Using on_value and off_value 


tf.one_hot(some_lists , depth = 4 , on_value=':)' , off_value=':(')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b':)', b':(', b':(', b':('],
       [b':(', b':)', b':(', b':('],
       [b':(', b':(', b':)', b':('],
       [b':(', b':(', b':(', b':)']], dtype=object)>

#### **Trying out different math functions**

* Squaring
* Log 
* Square Root

In [ ]:
# Create a new tensor 

n = tf.range(1 , 20)
n

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [ ]:
# Squaring it 
tf.square(n)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)>

In [ ]:
# Throw's error, this method requires non-int datatype

# tf.math.sqrt(n)

In [ ]:
# Finding the square root 
tf.math.sqrt(tf.cast(n , dtype = tf.float16))

<tf.Tensor: shape=(19,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ,
       3.162, 3.316, 3.465, 3.605, 3.742, 3.873, 4.   , 4.125, 4.242,
       4.36 ], dtype=float16)>

In [ ]:
# Finding the log, same error gotta change to float

# tf.math.log(n)

In [ ]:
# Solving the error 

tf.math.log(tf.cast(n , dtype = tf.float16))

<tf.Tensor: shape=(19,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 , 2.303 , 2.398 , 2.484 , 2.564 , 2.639 , 2.709 , 2.773 ,
       2.834 , 2.89  , 2.945 ], dtype=float16)>

#### **Exploring TensorFlow and NumPy's compatibility**

Tensorflow interacts beautifully with numpy arrays.

In [ ]:
# Create a tensor from a numpy array

n_tensor = tf.constant(np.array([3.8 , 7 , 10.2]))
n_tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.8,  7. , 10.2])>

In [ ]:
# Convert our tensor back to numpy array 

np.array(n_tensor) , type(np.array(n_tensor))

(array([ 3.8,  7. , 10.2]), numpy.ndarray)

In [ ]:
# Another way 
n_tensor.numpy()

array([ 3.8,  7. , 10.2])

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [ ]:
# The default types of each are different 
numpy_n = tf.constant(np.array([3.2 , 2.0 , 1]))
tensor_n = tf.constant([3.2 , 9. , 4])

# Checking the datatype's of each 
numpy_n.dtype , tensor_n.dtype

(tf.float64, tf.float32)

When we create a tensor from numpy the default datatype will be `float64` but by using tensorflow we will get `float32`. 

When computing with different tensors / numpy we should look out for the datatype error.

The major difference between a tensorflow tensor and an numpy array is that a TensorFlow tensor can be run on GPU or TPU. 

#### **Finding Access to GPU's**

In [ ]:
# Checking all the disks 

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Mar  1 09:10:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    28W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> 🧋 **Note:** If we have access to a CUDA-enabled GPU, tensorflow will automatically use it whenever possible. 

Exercise Notebooks are movied to the folder [Exericse_and_Extra-curriculum](https://github.com/ashikshafi08/Learning_Tensorflow/tree/main/Exericse_and_Extra-curriculum)

Happy Learning! 