<a href="https://colab.research.google.com/github/ashikshafi08/Learning_Tensorflow/blob/main/Notebooks/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) 

2.4.1


# Tensorflow Fundamentals 

In this notebook we are going to cover some of the fundamentals concepts of tensors using **TensorFlow**. 

Let's draw the outline what we are going to see, 
- Introduction to tensors 
- Getting information from tensors
- Manipulating tensors 
- Tensors and Numpy 
- Using `@tf.function`, a way to speed up regular python functions with tensorflow. 
- Using GPU's (or TPU's) with Tensorflow. 
- Exercise to muscle up tensorflow fundamentals skills.


## Introduction to tensors 

#### **Using `tf.constant` to create tensors**

In [80]:
# Creating tensors with tf.constant 

scalar = tf.constant(7)
scalar # Creating a scalar tensor

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [81]:
# Checking the number of dimensions of tensors 
scalar.ndim # No of dimensions

0

In [82]:
# Create a vector 
vector = tf.constant([10 , 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [83]:
# Checking the dimensions now 
vector.ndim 

1

In [84]:
# Now creating a matrix (has more than 1 dimensions)
matrix = tf.constant( [[1 , 2] , 
                       [3, 4]] )

matrix 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [85]:
# Checking the dimensions now 
matrix.ndim 

2

In [86]:
# Now manually choosing the dtype, and creating a matrix 

new_mat = tf.constant([ [1. , 2.] , 
                       [3. , 4.], 
                       [5. , 6.]] , dtype = tf.float16)
new_mat

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

There's not huge difference between `dtype = float32` and `dtype = float16`, it's mostly focuses on the memory allocation. 

Where `dtype = float32` storing these takes up larger space whereas `dtype = float16` takes up less space. 

We can use this to debug **datatype errors** or tensors being in wrong datatype, using this could fix it.

- Scalar --> Has 1 dimension
- Vector --> Has 2 dimensions
- Tensor --> Has 3 dimensions

In [87]:
# Now checking the dimensions of the above matrix 
new_mat.ndim

2

In [88]:
# Creating a tensor with more dimension

tensor = tf.constant([[[1 , 2 ,3],
                       [4,5,6]],
                      
                      [[7 , 8 , 9],
                       [10 , 11 , 12]],
                      
                      [[13 , 14 , 15] ,
                       [16 , 17 , 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [89]:
tensor.ndim

3

- Scalar : a single number 
- Vector : a number with direction 
- Matrix : a 2-dimensional array of numbers 
- Tensor : a n-dimensional array of numbers (where n can be any numbers)

#### **Using `tf.Variable` to create tensors** 

Let's call this changeable tensor, alike is Javascript using var brings us options on overwriitng or make changes to the tensor. 

But when we use const for creating a tensor, this reduces the chances of altering the tensor. 

In [90]:
changeable_tensor = tf.Variable([10 , 4])

# Creating one with constant
unchangeable_tensor = tf.constant([10 , 4])

changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>)

Making changes using `tf.Variable` using the `.assign()` function.

In [91]:
# Changing the value of the tensor 
changeable_tensor[0].assign(7)

# Looking into our tensor after changes 
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>

In [92]:
# Now trying the same in our unchangeable_tensor 

# unchangeable_tensor[0].assign(7) Throws error, uncomment to check the error.

Well it's obvious that we can't alter the tensor which are created using `tf.constant`. But why two ways of creating tensors exist even? 

Well while a Neural Net is been created, there are values should be changed whenever we want to and there should certain tensors locked up so that no one could make their changes on it. 

It might feel bit hectic, but good thing is that we need not to worry about assigning or structuring our neural net what values should it change and what it shouldn't. 

Behind the scenes these are taken care by TensorFlow.

#### **Creating random tensors**

Random tensors are tensors of some arbitary size which contain random numbers. 

In [93]:
# Creating 2 random (but same size)
random_1 = tf.random.Generator.from_seed(42)
random_2 = tf.random.Generator.from_seed(42)

# Giving in the shapes of how we want our tensors 
random_1 = random_1.normal(shape = (3,2))
random_2 = random_2.normal(shape = (3,2))

In [94]:
# Are they equal? 

random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Alright seems those two tensors are equal, but we asked for random tensors yet we got both of em equal, but why? 

In fact the values inside the random tensors aren't actually random, they are called as **pseudo values** which means they are getting geenrated because of the `from_seed()`.

It seeds the combinations and tensors depending upon the number we put it, this is because to attain reproducibility.

But how we fix this? If we can shuffle the order between them then they wont be identical. 



#### **Shuffling the order of tensors**

Shuffling comes in handy to prevent class Imbalance, which means if we fed images into a Neural Net in a strict plain order for instance, 

- Ramen (5000 pics)
- Cookie (1000 pics) 

Reading the images starting from Ramen and ends all of the 5000 pics and jumps next to Cookie, this won't give much work to our weight assignment. 

But if we can shuffle the images, our weights would be able to learn different classes at the same time. 

Now let's shuffle our tensors, valuable for when we want to shuffle our data so the inherent order won't affect our learning.

In [95]:
# Creating a tensor to shuffle

not_shuffled = tf.constant([[10 ,4],
                            [9 , 3],
                            [5 , 8]])

not_shuffled , not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  4],
        [ 9,  3],
        [ 5,  8]], dtype=int32)>, 2)

In [96]:
# Shuffling the tensor 
tf.random.shuffle(not_shuffled) # The order will be changed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 9,  3],
       [ 5,  8]], dtype=int32)>

In [97]:
tf.random.shuffle(not_shuffled) # The order will be changed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 9,  3],
       [10,  4]], dtype=int32)>

If we look into the shuffled and not_shuffled tensors we could find a common pattern that,
* Randomly shuffles a tensor along it's first dimension.

Which means it just changes the order of the rows, not the whole of the values inside the tensor. 

Also if we notice the two cells above with the same code `tf.random.shuffle(not_shuffled)`, the order is changed everytime when we run the cell.

**Using seed in the above shuffled example**

In [98]:
# Using the argument one 
tf.random.shuffle(not_shuffled , seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 5,  8],
       [ 9,  3]], dtype=int32)>

In [99]:
# Using a funciton called set_seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  3],
       [ 5,  8],
       [10,  4]], dtype=int32)>

In [100]:
# Creating 2 new tensor to play with 

#new_1_tensor = tf.random.Generator.from_seed(2)
#new_2_tensor = tf.random.Generator.from_seed(2)

# Now setting up the shape 
normal_tensor = tf.random.normal(shape = (3 , 2) , dtype = tf.float16) # (normal distributed values)
uniform_tensor = tf.random.normal(shape= (3 , 2) ,  dtype = tf.float16) # (uniformly distributed values)

normal_tensor , uniform_tensor


(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 0.0842  , -0.861   ],
        [ 0.3782  , -0.005196],
        [-0.4946  ,  0.6177  ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[-0.559 , -0.5347],
        [ 2.373 , -1.572 ],
        [ 0.8057, -0.834 ]], dtype=float16)>)

From reading the documentations, I understood about `tf.random.set_seed()`  is,  whenever we write that at first and the following code inside that cell will be generated with the same seed state. 




In [101]:
# Let's shuffle them! 

tf.random.set_seed(59) # Setting the seed here

# Shuffling 
norm_shuff = tf.random.shuffle(normal_tensor)
uni_shuff = tf.random.shuffle(uniform_tensor)

norm_shuff , uni_shuff

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 0.3782  , -0.005196],
        [-0.4946  ,  0.6177  ],
        [ 0.0842  , -0.861   ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 2.373 , -1.572 ],
        [-0.559 , -0.5347],
        [ 0.8057, -0.834 ]], dtype=float16)>)

In [102]:
# Now using the argument one 

tf.random.shuffle(normal_tensor , seed = 32) , tf.random.shuffle(uniform_tensor , seed = 32)

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[ 0.0842  , -0.861   ],
        [ 0.3782  , -0.005196],
        [-0.4946  ,  0.6177  ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[-0.559 , -0.5347],
        [ 0.8057, -0.834 ],
        [ 2.373 , -1.572 ]], dtype=float16)>)

In [103]:
# Using global and operation level both in conjuction

tf.random.set_seed(34) # Global level 
tf.random.shuffle(normal_tensor , seed=34)


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 0.0842  , -0.861   ],
       [-0.4946  ,  0.6177  ],
       [ 0.3782  , -0.005196]], dtype=float16)>

Alright summing up using, `tf.random.shuffle(any_tensor , seed = 32)` doesn't works. The results aren't reproducible. 

But when we use `tf.random.set_seed(42)`, the entire code written / wrapped inside that cell uses the seed rate and the results are reproducible. 

And using `tf.random.shuffle(any_tensor)` only shuffles the tensor along the **1st dimension**, which means just shuffles the rows. 

It look's like if we want our shuffled tensors to be in same order, we've got to use the global level and operation level random seed.

> If both the global and the operation seed arse set: Both seeds are used in conjuction to determine the random sequence.


#### **Creating Tensors from Numpy Array**

Certain functions of Numpy are even in TensorFlow, will look at them. 

In [104]:
# Creating a tensor of all ones / Numpy (np.ones) 

tf.ones([10 , 4]) # Pass in the shape

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [105]:
# Creating tensor for all zeros / Same numpy 

tf.zeros([8 , 5])

<tf.Tensor: shape=(8, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

**X** ---> Capital for matrix and tensors.
**y** ----> non-capital for vector.

In [106]:
# Turning numpy array into tensors
import numpy as np
numpy_A = np.arange(1 , 25 , dtype = np.float32)
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [107]:
# Putting into tf.constant converting into tensor
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)>

In [108]:
# Now using our desired shape as we need 

A = tf.constant(numpy_A , shape = (2 ,4 ,3))
B = tf.constant(numpy_A)

A , B

(<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],
 
        [[13., 14., 15.],
         [16., 17., 18.],
         [19., 20., 21.],
         [22., 23., 24.]]], dtype=float32)>,
 <tf.Tensor: shape=(24,), dtype=float32, numpy=
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float32)>)

In [109]:
tf.constant(numpy_A , shape = (3 , 8))


<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float32)>

If we look above, the shape should be decided with respect to the number of elements available in total. 

For instance, above we got **24 elements** and Creating different shapes we gotta makse sure are they equal when we multilply them

#### **Getting information from the tensors --> Tensor Attributes**

The common attributes we gotta keep an eye out are: 
- Shape 
- Rank 
- Size 
- Axis or dimension

In [110]:
# Creating a rank 4 tensor 

rank_4_tensor = tf.zeros(shape = [2 , 3 , 4 ,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [111]:
# Indexing into the above tensor 
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [116]:
# Printing out certain attributes for the above tensor 

def tensor_attr_print(a_tensor):
  '''
  Print's out different attribures of a tensor
  '''
  rank_4_tensor = a_tensor
  print(f'Elements along the 0th axis: {rank_4_tensor.shape[0]}')
  print(f'Elements along the last axis: {rank_4_tensor.shape[-1]}')
  print(f'Datatype of every element: {rank_4_tensor.dtype}')

  print(f'The shape of the tensor is: {rank_4_tensor.shape}')
  print(f'The dimension of the tensor is: {rank_4_tensor.ndim}')
  print(f'The size of the tensor(total no. of elements in the tensor): {tf.size(rank_4_tensor)}')

In [117]:
tensor_attr_print(rank_4_tensor)

Elements along the 0th axis: 2
Elements along the last axis: 5
Datatype of every element: <dtype: 'float32'>
The shape of the tensor is: (2, 3, 4, 5)
The dimension of the tensor is: 4
The size of the tensor(total no. of elements in the tensor): 120


#### **Indexing and expanding tensors**